export const workflowList: string[] = [
  'New',
  'Pending Compliance',
  'Pending Comex',
  'Pending user',
  'Pending Risk',
  'Completed',
  'Expired',
  'Awaiting Receipt',
  'Pending Rcci',
  'Rejected',
  'Accepted',
  'Open',
  'Closed',
  'Removed',
  'Pending Manager',
  'Accept under condition',
  'Awaiting NDAs',
];
